### ISSUE TITLE
Hydrator passes headers from original request to hydrate endpint

### ISSUE THREAD

**Issue by pike1212** [ory/oathkeeper#299]
**Is your feature request related to a problem? Please describe.**

Calls to the hydrate endpoint pass along all the headers of the original request including the authorization headers (including the original Authorization header which might not be valid for the hydrate call).

**Describe the solution you'd like**

I'd like the ability to configure it to not pass the headers

**Comment by aeneasr** [comment]
Do you want to simply disable this or also have the ability to overwrite headers?

**Comment by Sbou** [comment]
I think the issue is how the Hydrator receives the headers.

For me, the headers of the original request should be in the Header field of AuthenticationSession  and we would have differents headers for the Hydrator request itself.

I wrote a topic about this in the forum related to this issue.
https://community.ory.sh/t/how-to-use-headers/1382

What do you think about that ?

**Comment by aeneasr** [comment]
So in general this functionality is like a passthrough request - we're simply proxying the request to the upstream. There it is considered best practice to do it the way it's currently solved.

I understand however that you'd like to overwrite the, for example, authorization header. Could you maybe elaborate why having the original headers is a problem, or what you'd like to modify?

**Comment by pike1212** [comment]
I am not sure I would consider the hydrate request a simple proxy. Many of the headers in the context of the original request could be problematic for the service handling the hydrate request, i.e. `Authorization`, `Content-Type`, `Accept`. At a minimum, I think we need the ability to specify a list of a headers to overwrite / remove.

**Comment by aeneasr** [comment]
Right, that's a good point. Those should be (un-)set explicitly, especially `Accept` and `Content-Type`.

@piotrmsc what do you think? Would that cause an issue/regression in Kyma?

**Comment by DimitarPetrov** [comment]
We also hit the `Authorization` header problem. In our case, all the endpoints are secured by `RequestAuthentication` istio resource which automatically checks the Authorization header.

Oathkeeper is excluded from this policy and the policy trusts oathkeeper's id_token JWKS. However when we call oathkeeper it authenticates the request, but sends the original Authorization header to the hydrators which are inside the mesh and therefore secured with the RequestAuthentication, but the original Authorization header is not id_token therefore not trusted.

It is a bit of a mess when oahtkeeper forwards this header because all the issuers and authentication mechanisms cannot be isolated in the oathkeeper's authentication chain and strictly assume that everything down the flow will trust only id_tokens.
