### ISSUE TITLE
Clean up docker compose file

### ISSUE THREAD

**Issue by aeneasr** [ory/oathkeeper#324]
The current docker-compose file is very outdated and should be updated or removed.

**Comment by KarthikNayak** [comment]
Picking this up! Will update the compose file!

**Comment by KarthikNayak** [comment]
@aeneasr I see that the `Docker` file doesn't contain the build instructions, instead the build instructions lay in the `Makefile` this also means that just running `docker build .` fails. Is this expected behavior? 
If so, is it okay to move the build instruction to the `Dockerfile` ? This would get the `docker-compose` up and running.

**Comment by aeneasr** [comment]
Thank you @KarthikNayak ! Yeah right - please leave the current Docker Images as is! You can however add another Dockerfile named `Dockerfile-dc` with build instructions specifically for Docker Compose!
