### ISSUE TITLE
Git changes prevent <= v0.32.0-beta.1 from starting

### ISSUE THREAD

**Issue by mvanderlee** [ory/oathkeeper#397]
**Describe the bug**

Production system is down due to changes made to the schema documents on the master branch.
This appears to be due to the fact that the schema.json files reference the master branch.

i.e.: 
```
   "scope_strategy": {
      "$ref": "https://raw.githubusercontent.com/ory/oathkeeper/master/.schemas/scope_strategy.schema.json#"
    }
```
**Reproducing the bug**

Don't touch a system for months, things break anyway.

*Server logs*

```
{"access_url":"http://oathkeeper:4456/decisions/traefik","authentication_handler":"jwt","error":"authenticator matching this route is misconfigured or disabled","granted":false,"level":"warning","msg":"Unable to validate use of authentication handler","reason_id":"invalid_authentication_handler","time":"2020-04-06T13:06:27Z"}
```

*Server configuration*

Irrelevant

**Expected behavior**

Things to not break when schemas are change in a code base.

**Environment**
Irrelevant

**Additional context**

**Comment by aeneasr** [comment]
> **Environment**
>
> Irrelevant

No, that's not irrelevant. Please include your version.

**Comment by aeneasr** [comment]
This was by the way resolved a while back. ORY Oathkeeper no longer uses GitHub to fetch the Schema which is required to start / set up rules. I think this was changed a long time ago, which is why the version is in fact relevant, not irrelevant.

**Comment by mvanderlee** [comment]
It was a forked build from September 26, 2019.

And are you sure, the current schema still appears to reference GitHub.
```
{
  "$id": "https://raw.githubusercontent.com/ory/oathkeeper/master/.schema/authenticators.jwt.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "https://raw.githubusercontent.com/ory/oathkeeper/master/.schema/config.schema.json#/definitions/configAuthenticatorsJwt"
}
```

**Comment by aeneasr** [comment]
Yeah but the resolver no longer tries to fetch that from GitHub but instead loads everything from the local filesystem. You can try it out by running ORY Oathkeeper (a recent version) without internet access. We might want to rename the IDs as to avoid confusion though.

I'm sorry to say but we're don't have capacity to support forked projects. I have to check when this was fixed but as we support only the most recent version of "pre-release" software I don't think I can help here.

Keeping the old files around causes confusion with contributors because these are regularly changed when new features are added. This is bad anyways for systems that depend on these files as it might break at some point no matter if they're there or not.

**Comment by aeneasr** [comment]
https://github.com/ory/oathkeeper/commit/8cf6868b3e925e686769d43c912d5e52c6589a9b is the patch this was resolved with

**Comment by aeneasr** [comment]
I have renamed the Schema IDs with #398 so to avoid confusion over wether these files are loaded from remote or locally. It will also prevent accidental typos where ORY Oathkeeper tries to fetch it from remote because it's not available in the local stash.

**Comment by mvanderlee** [comment]
Thank you. I rebased and rebuilt. Systems are operational now.
