### ISSUE TITLE
Authenticate errors don't log the reason for the error

### ISSUE THREAD

**Issue by pike1212** [ory/oathkeeper#467]
**Is your feature request related to a problem? Please describe.**

When JWT validation fails, there is nothing in the logs that say why (i.e. token expired)

**Describe the solution you'd like**

Add the error reason to that log statement

**Comment by grantzvolsky** [comment]
To elaborate with a concrete example:

When Verifier returns from

https://github.com/ory/oathkeeper/blob/852fbc190f79c2848b4957dd945b1f4238fefbbb/credentials/verifier_default.go#L45

it correctly includes the reason. The reason is then lost in the Authenticator:

https://github.com/ory/oathkeeper/blob/852fbc190f79c2848b4957dd945b1f4238fefbbb/pipeline/authn/authenticator_jwt.go#L98

**Comment by aeneasr** [comment]
Ah yeah, we should definitely pass that error there. If you have an idea how to do that feel free to PR :)
