### ISSUE TITLE
Implement PASETO as a more secure alternative to JOSE

### ISSUE THREAD

**Issue by sycured** [ory/oathkeeper#566]
Hi, PASETO exists for a long time now and Okta implemented it as a more secure alternative to JOSE.

- https://paragonie.com/blog/2018/03/paseto-platform-agnostic-security-tokens-is-secure-alternative-jose-standards-jwt-etc
- https://developer.okta.com/blog/2019/10/17/a-thorough-introduction-to-paseto
- Library (Go): https://github.com/o1egl/paseto (listed on official website: https://paseto.io/)

Regards

**Comment by aeneasr** [comment]
Thank you for the idea! Could go into a bit more detail where this is used for example, or what parts of ORY Oathkeeper should support it? Is this for example integrated in Kubernetes, Istio, Linkerd?

**Comment by sycured** [comment]
With tools that I use/will use soon:
- Django: https://pypi.org/project/django-rest-paseto-auth/
- Hashicorp Vault: https://github.com/EasyWelfare/vault-paseto-secret-engine
- Kong: https://github.com/peter-evans/kong-plugin-paseto

And a lot of private webservices

**Comment by ycgambo** [comment]
I'm trying to implement ory ecosystem together with kong and istio for several months, and I'm getting stuck at find out a AuthService replacement of Kong instead of using Ambassador according to [this blog](https://www.ory.sh/api-access-control-kubernetes-cloud-native/). As the introduction says `If you want to use another API Gateway (Kong, Nginx, Envoy, AWS API Gateway, ...), Oathkeeper can also plug into that and act as its Policy Decision Point.`, It's quite confusing on how to use the `/judge` decision api. This issue here is the closest thing I reached so far if I don't want to write a homemade lua plugin for Kong.

**Comment by ycgambo** [comment]
this is what I'm trying to do: I hope I can use oathkeeper as ory service gateway to inject incoming request a X-User-ID header. So that I can easily unplug this service when I want to since it's not production ready.

![image](https://user-images.githubusercontent.com/23355083/104798806-8a663680-5804-11eb-8ccc-09f6f9ec64ba.png)

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
