### ISSUE TITLE
Ability to specify skip paths in the config

### ISSUE THREAD

**Issue by pike1212** [ory/oathkeeper#716]
**Is your feature request related to a problem? Please describe.**

There are certain paths we don't want to run any rules on and would like to configure these paths per service (currently run oathkeeper as a sidecar in k8s). Currently we have separate rules per deployment with different rules (a noop rule and a op rule).

**Describe the solution you'd like**

Open to suggestions, but a way to specify via an env var which paths to ignore I think is ideal.

**Comment by pike1212** [comment]
Any suggestions on how to make this easier then? This is a configuration nightmare since we want the same config rules with only different paths ignored per deployment.

**Comment by acobaugh** [comment]
It may be possible, and perhaps even preferable to package the oathkeeper rules with each application. That being said, 99% of our applications all follow the same pattern. `/` gets security applied, then a couple of endpoints (version, healthcheck, etc) need to be open without security. This is rather difficult to express with the current access_rules functionality, where we are required to write rules that don't overlap.

What we would like to see is a simple way to express path/method patterns that are ignored/passed-through by oathkeeper. With the prevalence of things like healthchecks and the like, I feel like this is functionality that should be supported and configurable via simple environment variables.

If patches for such functionality would be welcome, we'd be happy to submit a MR for review.

**Comment by aeneasr** [comment]
I agree this is truly a PITA right now! I think however that it would make more sense to support negative lookahead by using a different regex library. This would allow for a much better experience here! What fo you think?

**Comment by acobaugh** [comment]
So, my understanding is oathkeeper is already using a regex library that supports negative lookaheads (github.com/dlclark/regexp2), which seems to work, but it is a bit cumbersome. The second you have more than one path overlap, my brain hurts to think about the regex to cover that case! I think the real issue is the requirement that a given path shall match one and only one rule. There is no rule ordering - something like longest path wins, first match wins, etc.

**Comment by aeneasr** [comment]
Yes, currently push this onto the operator / admin because having rules around ordering makes things hard to grasp the more complexity you add. Therefore we always return an error if two rules match, to avoid "oh I forgot to re-arrange the order and now all my private info was leaked".

I think negative lookahead, while regex heavy, is for now the best option we have.
