### ISSUE TITLE
Implementation of keto_engine_acp_ory for keto v0.6+

### ISSUE THREAD

**Issue by gen1us2k** [ory/oathkeeper#945]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Oathkeeper has keto_engine_acp_ory authorizer but it works only for Keto v0.5 version.

### Describe your ideal solution

It would be best to implement an additional authorizer to enable support of Keto 0.6+ versions. 

### Workarounds or alternatives

I didn't find any

### Version

v0.38.23-beta.1

**Comment by aeneasr** [comment]
Absolutely! I believe that `remote_json` should already be compatible with the new version of Ory Keto!

**Comment by rrmistry** [comment]
After some digging found out the status for `keto_engine_acp_ory` authorizer.

Linking some of these discussions together:
https://community.ory.sh/t/problems-with-configuration-of-keto-engine-acp-ory-authorizer/2079/2

Summary:

> We want to deprecate `keto_engine_acp_ory` in favor of a generic `remote_json` handler which is why we haven’t shown it a lot of love recently. The problem is that `keto_engine_acp_ory` currently only works with regex routes if I recall correctly, because of the way we use RegexCaptureGroups to render `required_action` and so on. Hope this helps!

My additions:

`remote_json` mentioned above has since been renamed to `remote` as per docs: https://www.ory.sh/docs/oathkeeper/pipeline/authz#remote

Also mentioned in: https://github.com/ory/keto/discussions/1415
